import { useCallback, useEffect, useMemo, useState } from "react";

import { workspaceApi } from "../../../services/workspaceApi";
import { configurationIssue, inputSchema, workflowSchemas } from "../services/schemaPropagation";
import type { DatasetColumn, DatasetSchema, DatasetSummary, NodeType, Point, PreviewResult, WorkflowDefinition, WorkflowNode } from "../types";

const starterColumns = ["key", "summary", "status", "dcpsquad", "assignee"];
function starterWorkflow(dataset: DatasetSummary, columns: DatasetColumn[]): WorkflowDefinition { const available = new Set(columns.map((column) => column.name)); const selected = starterColumns.filter((column) => available.has(column)); const hasStatus = available.has("status"); const nodes: WorkflowNode[] = [{ id: "dataset-1", type: "dataset", config: { dataset: dataset.id, overview_position: { x: 100, y: 340 } }, position: { x: 100, y: 160 } }, ...(hasStatus ? [{ id: "filter-1", type: "filter" as const, config: { match: "all", rules: [{ id: "starter-status", column: "status", operator: "not_equals", value: "Done" }] }, position: { x: 390, y: 160 } }] : []), ...(selected.length ? [{ id: "select-1", type: "select" as const, config: { columns: selected }, position: { x: hasStatus ? 680 : 390, y: 160 } }] : []), { id: "output-1", type: "output", config: {}, position: { x: hasStatus && selected.length ? 970 : selected.length || hasStatus ? 680 : 390, y: 160 } }]; return { name: "Open Jira issues", nodes, edges: nodes.slice(1).map((node, index) => ({ id: `edge-${index}`, source: nodes[index].id, target: node.id })) }; }
const defaultConfig = (type: NodeType) => type === "filter" ? { match: "all", rules: [{ id: crypto.randomUUID(), column: "", operator: "equals", value: "" }] } : type === "group" ? { group_by: "", calculation: "count", value: "", result_name: "Issue count" } : type === "join" ? { dataset: "", left_column: "", right_column: "", join_type: "left" } : {};

export function useWorkspace() {
  const [workflow, setWorkflow] = useState<WorkflowDefinition>({ name: "Untitled workflow", nodes: [], edges: [] }); const [datasets, setDatasets] = useState<DatasetSummary[]>([]); const [schemaCache, setSchemaCache] = useState<Record<string, DatasetSchema | undefined>>({}); const [selectedId, setSelectedId] = useState<string | null>(null); const [preview, setPreview] = useState<PreviewResult | null>(null); const [previewOpen, setPreviewOpen] = useState(false); const [running, setRunning] = useState(false); const [dirty, setDirty] = useState(false); const [error, setError] = useState<string | null>(null); const [catalogLoading, setCatalogLoading] = useState(true);
  const datasetId = String(workflow.nodes.find((node) => node.type === "dataset")?.config.dataset ?? ""); const selectedNode = workflow.nodes.find((node) => node.id === selectedId) ?? null;
  const loadSchema = useCallback(async (id: string) => { if (!id || schemaCache[id]) return; try { const result = await workspaceApi.schema(id); setSchemaCache((current) => ({ ...current, [id]: result })); } catch (reason) { setError(reason instanceof Error ? reason.message : "Schema unavailable."); } }, [schemaCache]);
  useEffect(() => { workspaceApi.datasets().then(async (items) => { setDatasets(items); const jira = items.find((item) => item.name === "Jira Issues" && item.schema_name === "enp") ?? items.find((item) => item.name === "Jira Issues") ?? items[0]; if (jira) { const nextSchema = await workspaceApi.schema(jira.id); setSchemaCache({ [jira.id]: nextSchema }); setWorkflow(starterWorkflow(jira, nextSchema.columns)); setSelectedId("filter-1"); } }).catch(() => setError("DoraDB is unavailable. Start the database to load approved datasets.")).finally(() => setCatalogLoading(false)); }, []);
  useEffect(() => { void loadSchema(datasetId); for (const node of workflow.nodes) if (node.type === "join") void loadSchema(String(node.config.dataset ?? "")); }, [datasetId, workflow.nodes, loadSchema]);
  const nodeSchemas = useMemo(() => workflowSchemas(workflow, schemaCache), [workflow, schemaCache]);
  const nodeIssues = useMemo(() => Object.fromEntries(workflow.nodes.map((node) => [node.id, configurationIssue(node, inputSchema(workflow, node.id, nodeSchemas))])), [workflow, nodeSchemas]);
  const overviewPosition = useMemo(() => { const value = workflow.nodes.find((node) => node.type === "dataset")?.config.overview_position as Point | undefined; return value && Number.isFinite(value.x) && Number.isFinite(value.y) ? value : { x: 100, y: 340 }; }, [workflow.nodes]);
  const mutate = useCallback((change: (current: WorkflowDefinition) => WorkflowDefinition) => { setWorkflow((current) => change(current)); setDirty(true); setPreview(null); }, []);
  const moveOverview = useCallback((position: Point) => { setWorkflow((current) => ({ ...current, nodes: current.nodes.map((node) => node.type === "dataset" ? { ...node, config: { ...node.config, overview_position: position } } : node) })); setDirty(true); }, []);
  const updateNode = useCallback((id: string, config: Record<string, unknown>) => mutate((current) => ({ ...current, nodes: current.nodes.map((node) => node.id === id ? { ...node, config: { ...node.config, ...config } } : node) })), [mutate]);
  const moveNode = useCallback((id: string, position: Point) => mutate((current) => ({ ...current, nodes: current.nodes.map((node) => node.id === id ? { ...node, position } : node) })), [mutate]);
  const addNode = useCallback((type: NodeType, position?: Point, between?: { source: string; target: string }, initialConfig?: Record<string, unknown>) => { if (type === "dataset" && workflow.nodes.some((node) => node.type === "dataset")) return; if (type === "output" && workflow.nodes.some((node) => node.type === "output")) return; const id = `${type}-${crypto.randomUUID().slice(0, 6)}`; const last = workflow.nodes.at(-1); const node: WorkflowNode = { id, type, config: { ...(type === "dataset" && datasets[0] ? { dataset: datasets[0].id } : defaultConfig(type)), ...initialConfig }, position: position ?? { x: 120 + workflow.nodes.length * 270, y: 180 } }; mutate((current) => { const output = current.nodes.find((item) => item.type === "output"); const outputEdge = output ? current.edges.find((edge) => edge.target === output.id) : undefined; const insertion = between ?? (type !== "dataset" && type !== "output" && output && outputEdge ? { source: outputEdge.source, target: output.id } : undefined); if (insertion) { const target = current.nodes.find((item) => item.id === insertion.target); const shiftTarget = !position && target?.type === "output"; const placed = shiftTarget && target ? { ...node, position: target.position } : node; const nodes = [...current.nodes.map((item) => shiftTarget && item.id === insertion.target ? { ...item, position: { ...item.position, x: item.position.x + 300 } } : item), placed]; return { ...current, nodes, edges: [...current.edges.filter((edge) => !(edge.source === insertion.source && edge.target === insertion.target)), { id: `edge-${crypto.randomUUID().slice(0, 6)}`, source: insertion.source, target: id }, { id: `edge-${crypto.randomUUID().slice(0, 6)}`, source: id, target: insertion.target }] }; } return { ...current, nodes: [...current.nodes, node], edges: last ? [...current.edges, { id: `edge-${crypto.randomUUID().slice(0, 6)}`, source: last.id, target: id }] : current.edges }; }); setSelectedId(id); }, [datasets, mutate, workflow.nodes]);
  const deleteNode = useCallback((id: string) => mutate((current) => { const incoming = current.edges.filter((edge) => edge.target === id); const outgoing = current.edges.filter((edge) => edge.source === id); let edges = current.edges.filter((edge) => edge.source !== id && edge.target !== id); if (incoming.length === 1 && outgoing.length === 1 && incoming[0].source !== outgoing[0].target && !edges.some((edge) => edge.source === incoming[0].source && edge.target === outgoing[0].target)) edges = [...edges, { id: `edge-${crypto.randomUUID().slice(0, 6)}`, source: incoming[0].source, target: outgoing[0].target }]; return { ...current, nodes: current.nodes.filter((node) => node.id !== id), edges }; }), [mutate]);
  const disconnect = useCallback((id: string) => mutate((current) => ({ ...current, edges: current.edges.filter((edge) => edge.id !== id) })), [mutate]);
  const connect = useCallback((source: string, target: string) => { if (source === target) return; mutate((current) => { const sourceNode = current.nodes.find((node) => node.id === source); const targetNode = current.nodes.find((node) => node.id === target); if (!sourceNode || !targetNode || sourceNode.type === "output" || targetNode.type === "dataset") return current; const descendants = new Set<string>(); const collect = (id: string) => current.edges.filter((edge) => edge.source === id).forEach((edge) => { descendants.add(edge.target); collect(edge.target); }); collect(target); if (descendants.has(source)) return current; return { ...current, edges: [...current.edges.filter((edge) => edge.target !== target), { id: `edge-${crypto.randomUUID().slice(0, 6)}`, source, target }] }; }); }, [mutate]);
  const applyStarter = useCallback((kind: "blocked" | "unfinished" | "squad" | "sprint") => { const columns = schemaCache[datasetId]?.columns ?? []; const field = kind === "squad" ? columns.find((column) => /squad|team/i.test(column.name)) : kind === "sprint" ? columns.find((column) => /sprint/i.test(column.name)) : columns.find((column) => /status|state/i.test(column.name)); if (!field) { setError("This dataset does not have the field needed for that starter action."); return; } const output = workflow.nodes.find((node) => node.type === "output"); if (!output) return; if (kind === "squad" || kind === "sprint") { const existing = workflow.nodes.find((node) => node.type === "group"); if (existing) { updateNode(existing.id, { group_by: field.name, calculation: "count", value: "", result_name: "Issue count" }); setSelectedId(existing.id); } else addNode("group", { x: output.position.x - 270, y: output.position.y }, { source: workflow.edges.find((edge) => edge.target === output.id)?.source ?? workflow.nodes[0].id, target: output.id }, { group_by: field.name, calculation: "count", value: "", result_name: "Issue count" }); return; } else { const existing = workflow.nodes.find((node) => node.type === "filter"); const rule = { id: crypto.randomUUID(), column: field.name, operator: kind === "blocked" ? "equals" : "not_equals", value: kind === "blocked" ? "Blocked" : "Done" }; if (existing) { updateNode(existing.id, { match: "all", rules: [rule] }); setSelectedId(existing.id); } else addNode("filter", { x: output.position.x - 270, y: output.position.y }, { source: workflow.edges.find((edge) => edge.target === output.id)?.source ?? workflow.nodes[0].id, target: output.id }, { match: "all", rules: [rule] }); } }, [addNode, datasetId, schemaCache, setError, updateNode, workflow]);
  const run = useCallback(async () => { setRunning(true); setError(null); try { const result = await workspaceApi.run(workflow); setPreview(result); setPreviewOpen(true); return result; } catch (reason) { setError(reason instanceof Error ? reason.message : "The workflow could not run."); return null; } finally { setRunning(false); } }, [workflow]);
  const save = useCallback(async () => { setError(null); try { const saved = await workspaceApi.save(workflow); setWorkflow(saved); setDirty(false); } catch (reason) { setError(reason instanceof Error ? reason.message : "The workflow could not be saved."); } }, [workflow]); const setName = (name: string) => mutate((current) => ({ ...current, name })); const dataset = useMemo(() => datasets.find((item) => item.id === datasetId), [datasetId, datasets]);
  return { workflow, datasets, schema: schemaCache[datasetId] ?? null, schemas: schemaCache, nodeSchemas, nodeIssues, overviewPosition, dataset, selectedNode, selectedId, preview, previewOpen, running, dirty, error, catalogLoading, setSelectedId, setPreviewOpen, setError, updateNode, moveNode, addNode, deleteNode, disconnect, connect, moveOverview, applyStarter, run, save, setName };
}