import { GripHorizontal, Info, TableProperties } from "lucide-react";
import { useRef, type PointerEvent } from "react";

import type { DatasetSchema, DatasetSummary, Point } from "../types";

const fieldHint = (name: string) => { const lower = name.toLowerCase(); if (lower.includes("status")) return "Current state of the issue"; if (lower.includes("sprint")) return "Sprint associated with the issue"; if (lower.includes("squad") || lower.includes("team")) return "Team responsible for the issue"; if (lower.includes("assignee")) return "Person responsible for the work"; if (lower.includes("priority")) return "Delivery priority"; if (lower.includes("type")) return "Type of work, such as bug, story, or task"; if (lower.includes("created")) return "When the record was created"; return "Available approved field"; };
export function DatasetOverview({ dataset, schema, position, scale, onMove, onViewFields }: { dataset?: DatasetSummary; schema: DatasetSchema | null; position: Point; scale: number; onMove: (point: Point) => void; onViewFields: () => void }) {
  const drag = useRef<{ x: number; y: number; left: number; top: number } | null>(null); if (!dataset || !schema) return null; const useful = schema.columns.filter((column) => /status|sprint|squad|team|assignee|priority|created|type|point/i.test(column.name)).slice(0, 6);
  const start = (event: PointerEvent<HTMLElement>) => { event.stopPropagation(); drag.current = { x: event.clientX, y: event.clientY, left: position.x, top: position.y }; event.currentTarget.setPointerCapture(event.pointerId); };
  const move = (event: PointerEvent<HTMLElement>) => { if (!drag.current) return; onMove({ x: Math.max(30, drag.current.left + (event.clientX - drag.current.x) / scale), y: Math.max(55, drag.current.top + (event.clientY - drag.current.y) / scale) }); };
  return <section className="dataset-overview" aria-label="Dataset Overview"><header onPointerDown={start} onPointerMove={move} onPointerUp={() => { drag.current = null; }}><span><TableProperties size={16} /></span><div><small>DATASET OVERVIEW</small><h2>{dataset.name}</h2></div><GripHorizontal size={16} /></header><div className="dataset-overview__body"><p>{/jira issues/i.test(dataset.name) ? "Issue-level delivery data from Jira." : dataset.description}</p><div className="dataset-overview__facts"><span>{schema.columns.length} fields</span><span>{dataset.relation_type.replaceAll("_", " ")}</span></div><h3><Info size={12} /> Key fields</h3><div className="dataset-overview__fields">{useful.map((column) => <span key={column.name}><strong>{column.label}</strong><small>{fieldHint(column.name)}</small></span>)}</div><button className="dataset-overview__all-fields" onClick={(event) => { event.stopPropagation(); onViewFields(); }}>View all fields in Select Columns</button></div></section>;
}