import { AlertTriangle, Check, ChevronRight, GitMerge, Layers3, Plus, SlidersHorizontal, X } from "lucide-react";
import { useMemo } from "react";

import { FilterRuleEditor } from "../../filter/FilterRuleEditor";
import { DoraDataMap } from "./DoraDataMap";
import { compatibleJoinFields, inputSchema } from "../services/schemaPropagation";
import type { DatasetColumn, DatasetSchema, DatasetSummary, FilterRule, WorkflowDefinition, WorkflowNode } from "../types";
import { NODE_LABELS } from "../types";

interface Props { node: WorkflowNode | null; workflow: WorkflowDefinition; datasets: DatasetSummary[]; schema: DatasetSchema | null; schemas: Record<string, DatasetSchema | undefined>; nodeSchemas: Record<string, DatasetColumn[]>; nodeIssue?: string; onClose: () => void; onUpdate: (config: Record<string, unknown>) => void; onVisualize?: () => void; }
function rulesFor(node: WorkflowNode): FilterRule[] { const configured = node.config.rules as FilterRule[] | undefined; return configured?.length ? configured : [{ id: `${node.id}-rule-1`, column: String(node.config.column ?? ""), operator: String(node.config.operator ?? "equals"), value: node.config.value ?? "" }]; }
const label = (name: string) => name.replaceAll("_", " ");
const numeric = (column?: DatasetColumn) => Boolean(column?.numeric || /int|numeric|decimal|real|double|float/i.test(column?.data_type ?? ""));

export function NodeConfigPanel({ node, workflow, datasets, schema, schemas, nodeSchemas, nodeIssue, onClose, onUpdate, onVisualize }: Props) {
  const selectedColumns = useMemo(() => new Set((node?.config.columns as string[] | undefined) ?? []), [node?.config.columns]);
  if (!node) return null;
  const incoming = inputSchema(workflow, node.id, nodeSchemas);
  const selectable = node.type === "dataset" ? schema?.columns ?? [] : incoming;
  const sourceDatasetId = String(workflow.nodes.find((item) => item.type === "dataset")?.config.dataset ?? "");
  const sourceColumns = schemas[sourceDatasetId]?.columns ?? schema?.columns ?? [];
  const filterRules = node.type === "filter" ? rulesFor(node) : [];
  const updateRule = (index: number, rule: FilterRule) => onUpdate({ rules: filterRules.map((current, ruleIndex) => ruleIndex === index ? rule : current) });
  const addRule = () => onUpdate({ rules: [...filterRules, { id: crypto.randomUUID(), column: "", operator: "equals", value: "" }] });
  const joinDatasetId = String(node.config.dataset ?? ""); const joinColumns = schemas[joinDatasetId]?.columns ?? []; const leftColumn = String(node.config.left_column ?? ""); const compatible = compatibleJoinFields(incoming, joinColumns, leftColumn);
  const calculation = String(node.config.calculation ?? "count"); const valueColumn = incoming.find((column) => column.name === node.config.value);
  return <aside className="config-panel">
    <header><div><span><SlidersHorizontal size={14} /> Configure step</span><h2>{NODE_LABELS[node.type]}</h2></div><button onClick={onClose} aria-label="Close configuration"><X size={18} /></button></header>
    <div className="config-content">
      {nodeIssue && <div className="config-live-warning" role="status"><AlertTriangle size={15} /><div><strong>Needs attention</strong><span>{nodeIssue}</span></div></div>}
      {node.type === "dataset" && <div className="field-group"><label>Approved dataset</label><p>Choose the company data you want to prepare.</p><select value={String(node.config.dataset ?? "")} onChange={(event) => onUpdate({ dataset: event.target.value })}><option value="">Choose a dataset</option>{datasets.map((dataset) => <option key={dataset.id} value={dataset.id}>{dataset.name} · {dataset.column_count} fields</option>)}</select>{schema && <div className="dataset-detail"><strong>{schema.dataset.name}</strong><span>{schema.columns.length} available columns</span><small>{schema.dataset.description}</small></div>}<DoraDataMap datasets={datasets} selectedId={String(node.config.dataset ?? "")} onChoose={(dataset) => onUpdate({ dataset })} /></div>}
      {node.type === "filter" && <div className="filter-builder"><div className="field-group"><label>How should conditions work?</label><p>Only fields available from the previous step are shown.</p><select value={String(node.config.match ?? "all")} onChange={(event) => onUpdate({ match: event.target.value })}><option value="all">Match all conditions (AND)</option><option value="any">Match any condition (OR)</option></select></div>{!incoming.length && <p className="config-warning">Connect this filter to a previous step first.</p>}<div className="filter-rule-list">{filterRules.map((rule, index) => <FilterRuleEditor key={rule.id} rule={rule} index={index} sourceDatasetId={sourceDatasetId} columns={incoming} sourceColumns={sourceColumns} canRemove={filterRules.length > 1} onChange={(next) => updateRule(index, next)} onRemove={() => onUpdate({ rules: filterRules.filter((_, ruleIndex) => ruleIndex !== index) })} />)}</div><button className="add-condition" onClick={addRule}><Plus size={14} /> Add condition</button></div>}
      {node.type === "select" && <div className="field-group"><label>Columns to keep</label><p>Only fields from the previous step can be kept.</p><div className="column-actions"><button onClick={() => onUpdate({ columns: selectable.map((column) => column.name) })}>Select all</button><button onClick={() => onUpdate({ columns: [] })}>Clear</button></div><div className="column-picker">{selectable.map((column) => <label key={column.name}><input type="checkbox" checked={selectedColumns.has(column.name)} onChange={() => onUpdate({ columns: selectedColumns.has(column.name) ? [...selectedColumns].filter((name) => name !== column.name) : [...selectedColumns, column.name] })} /><span><strong>{column.label}</strong><small>{column.data_type}</small></span><Check size={14} /></label>)}</div></div>}
      {node.type === "group" && <div className="group-builder"><div className="output-config__title"><span><Layers3 size={18} /></span><div><h3>Summarize data</h3><p>Turn records into a simple grouped result.</p></div></div><label>Group by<select value={String(node.config.group_by ?? "")} onChange={(event) => onUpdate({ group_by: event.target.value })}><option value="">Choose a field</option>{incoming.map((column) => <option key={column.name} value={column.name}>{column.label}</option>)}</select></label><label>Show<select value={calculation} onChange={(event) => onUpdate({ calculation: event.target.value, value: ["count", "count_distinct"].includes(event.target.value) ? "" : node.config.value })}><option value="count">Number of records</option><option value="count_distinct">Number of distinct values</option>{incoming.some((column) => numeric(column)) && <><option value="sum">Total</option><option value="average">Average</option><option value="minimum">Minimum</option><option value="maximum">Maximum</option></>}</select></label>{calculation !== "count" && <label>Using field<select value={String(node.config.value ?? "")} onChange={(event) => onUpdate({ value: event.target.value })}><option value="">Choose a field</option>{incoming.filter((column) => calculation === "count_distinct" || numeric(column)).map((column) => <option key={column.name} value={column.name}>{column.label}</option>)}</select></label>}<label>Result label<input value={String(node.config.result_name ?? "Issue count")} onChange={(event) => onUpdate({ result_name: event.target.value })} placeholder="e.g. Issue count" /></label>{Boolean(node.config.group_by) && <div className="group-preview">The result will show one row per <strong>{label(String(node.config.group_by))}</strong> with <strong>{String(node.config.result_name || (valueColumn ? `${calculation} ${valueColumn.label}` : "issue count"))}</strong>.</div>}</div>}
      {node.type === "join" && <div className="join-builder"><div className="output-config__title"><span><GitMerge size={18} /></span><div><h3>Combine data</h3><p>Add matching information from another approved source.</p></div></div><label>Add data from<select value={joinDatasetId} onChange={(event) => onUpdate({ dataset: event.target.value, left_column: "", right_column: "" })}><option value="">Choose approved data</option>{datasets.filter((dataset) => dataset.id !== sourceDatasetId).map((dataset) => <option key={dataset.id} value={dataset.id}>{dataset.name} · {dataset.column_count} fields</option>)}</select></label>{joinDatasetId && <><label>Current data field<select value={leftColumn} onChange={(event) => onUpdate({ left_column: event.target.value, right_column: "" })}><option value="">Choose a field</option>{incoming.map((column) => <option key={column.name} value={column.name}>{column.label}</option>)}</select></label><label>Match with<select value={String(node.config.right_column ?? "")} onChange={(event) => onUpdate({ right_column: event.target.value })}><option value="">Choose a compatible field</option>{compatible.map((column) => <option key={column.name} value={column.name}>{column.label}</option>)}</select></label><label>Keep<select value={String(node.config.join_type ?? "left")} onChange={(event) => onUpdate({ join_type: event.target.value })}><option value="left">All current records — add matches when available</option><option value="inner">Matching records only</option></select></label><div className="join-preview">Preview will keep the current workflow data and add fields from <strong>{datasets.find((dataset) => dataset.id === joinDatasetId)?.name}</strong>. Only compatible field types are offered.</div></>}</div>}
      {node.type === "output" && <div className="output-config"><span><Check size={22} /></span><h3>Your result is ready</h3><p>Run the workflow to refresh the preview, then turn the processed output into a dashboard.</p><ul><li><ChevronRight size={14} /> Preview up to 100 rows</li><li><ChevronRight size={14} /> Keep DoraDB read-only</li><li><ChevronRight size={14} /> Visualize processed results</li></ul>{onVisualize && <button className="visualize-output-cta" onClick={onVisualize}>Visualize Data <ChevronRight size={14} /></button>}</div>}
      {node.type === "calculate" && <div className="output-config"><h3>Planned operation</h3><p>This step will be enabled after the core prepare-data workflow is verified.</p></div>}
    </div>
    <footer><button className="apply-button" onClick={onClose}><Check size={15} /> Apply changes</button><small>Changes are stored in the workflow definition, never as SQL.</small></footer>
  </aside>;
}