import { GitMerge, LocateFixed, Minus, Plus, Sparkles, Unplug } from "lucide-react";
import { useMemo, useRef, useState, type DragEvent } from "react";
import type { DatasetSchema, DatasetSummary, NodeType, Point, PreviewResult, WorkflowDefinition } from "../types";
import { DatasetOverview } from "./DatasetOverview";
import { WorkflowNodeCard } from "./WorkflowNodeCard";

interface Props { workflow: WorkflowDefinition; selectedId: string | null; dataset?: DatasetSummary; schema: DatasetSchema | null; preview: PreviewResult | null; overviewPosition: Point; onMoveOverview: (point: Point) => void; nodeIssues: Record<string, string | undefined>; panelOpen: boolean; onSelect: (id: string | null) => void; onMove: (id: string, point: Point) => void; onAdd: (type: NodeType, point?: Point, between?: { source: string; target: string }) => void; onDelete: (id: string) => void; onConnect: (source: string, target: string) => void; onDisconnect: (id: string) => void; }
const distanceToSegment = (point: Point, start: Point, end: Point) => { const dx = end.x - start.x; const dy = end.y - start.y; const ratio = Math.max(0, Math.min(1, ((point.x - start.x) * dx + (point.y - start.y) * dy) / (dx * dx + dy * dy || 1))); return Math.hypot(point.x - (start.x + ratio * dx), point.y - (start.y + ratio * dy)); };
export function WorkflowCanvas({ workflow, selectedId, dataset, schema, preview, overviewPosition, onMoveOverview, nodeIssues, panelOpen, onSelect, onMove, onAdd, onDelete, onConnect, onDisconnect }: Props) {
  const canvasRef = useRef<HTMLDivElement>(null); const [pendingSource, setPendingSource] = useState<string | null>(null); const [scale, setScale] = useState(1); const [insertEdge, setInsertEdge] = useState<string | null>(null); const nodeMap = useMemo(() => new Map(workflow.nodes.map((node) => [node.id, node])), [workflow.nodes]);
  const locateEdge = (point: Point) => workflow.edges.find((edge) => { const source = nodeMap.get(edge.source); const target = nodeMap.get(edge.target); return source && target && distanceToSegment(point, { x: source.position.x + 238, y: source.position.y + 71 }, { x: target.position.x, y: target.position.y + 71 }) < 68; });
  const pointFor = (event: DragEvent) => { const rect = canvasRef.current?.getBoundingClientRect(); return { x: (event.clientX - (rect?.left ?? 0)) / scale, y: (event.clientY - (rect?.top ?? 0)) / scale }; };
  const drop = (event: DragEvent) => { event.preventDefault(); const type = event.dataTransfer.getData("application/zara-node") as NodeType; if (!type) return; const point = pointFor(event); const edge = locateEdge(point); onAdd(type, { x: point.x - 120, y: point.y - 70 }, edge ? { source: edge.source, target: edge.target } : undefined); setInsertEdge(null); };
  return <main ref={canvasRef} className="workflow-canvas" onDragOver={(event) => { event.preventDefault(); const edge = locateEdge(pointFor(event)); setInsertEdge(edge?.id ?? null); }} onDragLeave={() => setInsertEdge(null)} onDrop={drop} onPointerDown={(event) => { const target = event.target as Element; if (target === event.currentTarget || target.classList.contains("canvas-world") || target.classList.contains("edge-layer")) onSelect(null); }}>
    <div className="canvas-title"><div><span>WORKFLOW CANVAS</span><strong>{workflow.nodes.length} steps</strong></div>{pendingSource && <p>Choose an input handle to finish the connection</p>}</div>
    {!workflow.nodes.length && <div className="canvas-empty"><span><Sparkles size={26} /></span><h1>Prepare your data</h1><p>Start by choosing an approved DoraDB dataset.</p><button onClick={(event) => { event.stopPropagation(); onAdd("dataset"); }}><Plus size={16} /> Add Dataset</button><ol><li>Add your data</li><li>Add an operation</li><li>Connect the steps</li><li>Run your workflow</li></ol></div>}
    <div className="canvas-world" style={{ transform: `scale(${scale})` }}><svg className="edge-layer" width="1800" height="900" aria-label="Workflow connections"><defs><marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="5" markerHeight="5" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" /></marker></defs>{workflow.edges.map((edge) => { const source = nodeMap.get(edge.source); const target = nodeMap.get(edge.target); if (!source || !target) return null; const x1 = source.position.x + 238; const y1 = source.position.y + 71; const x2 = target.position.x; const y2 = target.position.y + 71; const bend = Math.max(45, Math.abs(x2 - x1) / 2); return <path key={edge.id} className={`workflow-edge ${target.type === "join" ? "workflow-edge--join" : ""} ${insertEdge === edge.id ? "workflow-edge--insert" : ""}`} d={`M${x1},${y1} C${x1 + bend},${y1} ${x2 - bend},${y2} ${x2},${y2}`} markerEnd="url(#arrow)" role="button" aria-label="Disconnect this connection" onClick={(event) => { event.stopPropagation(); onDisconnect(edge.id); }} />; })}{workflow.nodes.filter((node) => node.type === "join" && node.config.dataset).map((node) => <path key={`join-source-${node.id}`} className="workflow-edge workflow-edge--join-source" d={`M${node.position.x + 119},${node.position.y - 28} L${node.position.x + 119},${node.position.y - 2}`} markerEnd="url(#arrow)" />)}</svg>{workflow.nodes.map((node) => <WorkflowNodeCard key={node.id} node={node} dataset={node.type === "dataset" ? dataset : undefined} selected={node.id === selectedId} rowCount={node.type === "output" && preview ? preview.row_count : undefined} issue={nodeIssues[node.id]} running={Boolean(preview === null && false)} onSelect={() => onSelect(node.id)} onMove={(point) => onMove(node.id, point)} onDelete={() => onDelete(node.id)} onStartConnection={() => setPendingSource(node.id)} onFinishConnection={() => { if (pendingSource) { onConnect(pendingSource, node.id); setPendingSource(null); } }} />)}{workflow.nodes.filter((node) => node.type === "join" && node.config.dataset).map((node) => <div key={`join-label-${node.id}`} className="join-source-marker" style={{ transform: `translate(${node.position.x + 68}px, ${node.position.y - 60}px)` }}><GitMerge size={12} /> Added approved data</div>)}{workflow.nodes.find((node) => node.type === "dataset") && <div className="dataset-overview-anchor" style={{ transform: `translate(${overviewPosition.x}px, ${overviewPosition.y}px)` }}><DatasetOverview dataset={dataset} schema={schema} position={overviewPosition} scale={scale} onMove={onMoveOverview} onViewFields={() => { const selectNode = workflow.nodes.find((node) => node.type === "select"); if (selectNode) onSelect(selectNode.id); }} /></div>}</div>
    {!panelOpen && <div className="canvas-controls"><button onClick={() => setScale((value) => Math.min(1.25, value + .1))}><Plus size={15} /></button><span>{Math.round(scale * 100)}%</span><button onClick={() => setScale((value) => Math.max(.65, value - .1))}><Minus size={15} /></button><button onClick={() => setScale(1)}><LocateFixed size={15} /></button><button title="Click a connection to disconnect it" aria-label="Connection help"><Unplug size={14} /></button></div>}
  </main>;
}